# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost', 'http://127.0.0.1', 'https://example.com', 'https://*.googleusercontent.com', 'https://*.googleapis.com']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['*']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost', 'http://127.0.0.1', 'https://example.com', 'https://*.googleusercontent.com', 'https://*.googleapis.com']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['*']
            max_age: 3600
