# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']  # Changez ceci pour tester
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['*']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']  # Changez ceci pour tester
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['*']
            max_age: 3600
