# config/packages/security.yaml

security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User:
            algorithm: auto

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\GoogleAuthenticator
            form_login:
                login_path: app_login
                check_path: /login_check
                default_target_path: app_home
                username_parameter: _username
                password_parameter: _password
            logout:
                path: app_logout
                target: app_home
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 604800
                path: /

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/connect-google, roles: PUBLIC_ACCESS }
        - { path: ^/connect-google/check, roles: PUBLIC_ACCESS }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
