controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml

# config/routes.yaml
connect_google:
    path: /connect-google
    controller: App\Controller\OAuthController::connectGoogle

connect_google_check:
    path: /connect-google/check
    controller: App\Controller\OAuthController::connectGoogleCheck

